// Catalogue entries: platform. Shape and rules: ../index.js.

module.exports = [
  { route: "GET /api/catalogue", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/admin/app-visitors", summary: null, reach: "read", role: null, agent: false },
  { route: "PUT /api/admin/app-visitors/blocks/:agent", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/admin/sandboxes/purge", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/approvals/decision", summary: null, reach: "private", role: null, agent: false },
  { route: "DELETE /api/collections/:collectionId", summary: null, reach: "private", role: null, agent: false },
  { route: "PATCH /api/collections/:collectionId", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/commons/assets", summary: null, reach: "read", role: null, agent: false },
  { route: "DELETE /api/commons/assets/:assetId", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/commons/assets/:assetId", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/config", summary: null, reach: "read", role: null, agent: false },
  { route: "PATCH /api/config", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/content-changes/undo", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/estate/map", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/events", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/follows", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/health", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/open-calls/:callId/applications", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/open-calls/:callId/applications", summary: null, reach: "private", role: null, agent: false },
  { route: "DELETE /api/open-calls/:callId/applications/:applicationId", summary: null, reach: "private", role: null, agent: false },
  { route: "PATCH /api/open-calls/:callId/applications/:applicationId", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/stats", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/track", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/trash", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/work-status", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /og", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /og/*splat", summary: null, reach: "read", role: null, agent: false },
]
