// Catalogue entries: spaces. Shape and rules: ../index.js.

module.exports = [
  { route: "GET /api/spaces", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces", summary: null, reach: "private", role: null, agent: false },
  { route: "DELETE /api/spaces/:spaceId", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId", summary: null, reach: "read", role: null, agent: false },
  { route: "PATCH /api/spaces/:spaceId", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/bundle", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/changes", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/collections", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/collections", summary: null, reach: "private", role: null, agent: false },
  { route: "PUT /api/spaces/:spaceId/collections/order", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/contents", summary: null, reach: "read", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/events", summary: null, reach: "read", role: null, agent: false },
  { route: "DELETE /api/spaces/:spaceId/github-link", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/github-link", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/github-link", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/inscriptions", summary: null, reach: "private", role: null, agent: false },
  { route: "DELETE /api/spaces/:spaceId/inscriptions/:id", summary: null, reach: "private", role: null, agent: false },
  { route: "PUT /api/spaces/:spaceId/inscriptions/:id/mark", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/inscriptions/:id/tunnel", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/live", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/ops", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/ops", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/projects", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/projects", summary: null, reach: "private", role: null, agent: false },
  { route: "PUT /api/spaces/:spaceId/projects/order", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/proposals", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/restore-snapshot", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/scene", summary: null, reach: "read", role: null, agent: false },
  { route: "PUT /api/spaces/:spaceId/scene", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/settings", summary: null, reach: "read", role: null, agent: false },
  { route: "PUT /api/spaces/:spaceId/settings", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/signal", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/signal", summary: null, reach: "private", role: null, agent: false },
  { route: "GET /api/spaces/:spaceId/snapshots", summary: null, reach: "read", role: null, agent: false },
  { route: "POST /api/spaces/:spaceId/touch", summary: null, reach: "private", role: null, agent: false },
  { route: "POST /api/spaces/bundle", summary: null, reach: "private", role: null, agent: false },
]
