#!/usr/bin/env bash
# nginx-conf.sh — turn the repo's nginx.conf (the client image's server block) into a standby
# host's nginx config, changing only what the host makes different:
#
#   listen 8080;                 -> listen <listen>;          (e.g. 127.0.0.1:8080)
#   root /usr/share/nginx/html;  -> root <release>/dist;
#   http://server:4000           -> http://<upstream>          (e.g. 127.0.0.1:4000)
#
# plus a minimal main config (pid, temp paths, logs under <run-dir>) that includes it. Every
# replacement must match at least once, and the result must pass `nginx -t`, or it stops:
# if prod's nginx.conf changes shape, this fails loudly instead of serving something else.
#
#   nginx-conf.sh <nginx-bin> <release-dir> <listen> <upstream> <run-dir> <out-file>
set -euo pipefail
nginx=${1:?nginx binary}; rel=${2:?release dir}; listen=${3:?listen}; up=${4:?upstream}
run=${5:?run dir}; out=${6:?out file}

src="$rel/nginx.conf.prod"
[[ -f $src && -d $rel/dist ]] || { echo "no nginx.conf.prod or dist in $rel" >&2; exit 1; }
for pat in '^[[:space:]]*listen 8080;' '^[[:space:]]*root /usr/share/nginx/html;' 'http://server:4000'; do
  grep -qE "$pat" "$src" || { echo "prod nginx.conf no longer contains: $pat" >&2; exit 1; }
done

mkdir -p "$run"/{tmp,logs} "$(dirname "$out")"
server_block="$(dirname "$out")/server.conf"
sed -E \
  -e "s#^([[:space:]]*)listen 8080;#\\1listen $listen;#" \
  -e "s#^([[:space:]]*)root /usr/share/nginx/html;#\\1root $rel/dist;#" \
  -e "s#http://server:4000#http://$up#g" \
  "$src" > "$server_block"

mime="$(cd "$(dirname "$nginx")/.." && pwd)/etc/nginx/mime.types"
[[ -f $mime ]] || mime=/opt/homebrew/etc/nginx/mime.types
cat > "$out" <<CONF
# generated by scripts/standby/nginx-conf.sh from $src — do not edit, regenerate
worker_processes 2;
pid $run/nginx.pid;
error_log $run/logs/error.log warn;
events { worker_connections 1024; }
http {
  include $mime;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;
  access_log $run/logs/access.log;
  client_body_temp_path $run/tmp/body;
  proxy_temp_path $run/tmp/proxy;
  fastcgi_temp_path $run/tmp/fastcgi;
  uwsgi_temp_path $run/tmp/uwsgi;
  scgi_temp_path $run/tmp/scgi;
  include $server_block;
}
CONF
"$nginx" -t -c "$out" -p "$run"
echo "nginx-conf: $out (server block $server_block)"
