import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { smoothstep } from '../ritualClock.js'

// Sequence 04 — test pattern.
//
// Replaces Assembly, on direction: white world, black lines, and the visitor
// walking through them.
//
// ---- WHAT THE REFERENCE ACTUALLY IS ----------------------------------------
//
// The artist's reference is an Ikeda test-pattern shader. It was rendered and
// read frame by frame before any of this was written, and four things in it are
// not obvious from the source:
//
//   1. There are exactly TWO bands. `fract(st.y * cols * 0.5)` with cols = 2
//      reduces to fract(st.y), which for a normalised screen splits it into one
//      top half and one bottom half. Not a stack of rows — a single seam.
//   2. `freq += random(floor(st.y))` adds a CONSTANT: floor(st.y) is 0 across
//      the whole frame. Every bar in the image sits on one cell grid.
//   3. The cell size re-rolls once a second (`random(floor(u_time))`) and swings
//      hard — measured at 108 cells across one second and 33 the next, so the
//      pattern jumps between fine and chunky rather than drifting.
//   4. The scroll is `floor(t)`. It steps in whole cells. It stutters, and that
//      stutter is most of what makes it read as a machine rather than a wave.
//
// Bars are ~20% of cells, and adjacent lit cells MERGE — that is where the
// varied bar widths come from, not from a width distribution.
//
// Nothing is ported. The shader is published under terms that forbid use in a
// project, so what is taken is the reading above: a cell grid, a fifth of it
// lit, runs that merge, two counter-stepping bands, a periodic re-roll of the
// grid itself. All of it re-derived here in three dimensions.
//
// ---- WHAT MAKES IT 3D ------------------------------------------------------
//
// The bars become SLABS standing in a white void, in ranks going away from the
// viewer, and the pattern does not scroll — the visitor travels through it. That
// swap is the whole translation. In two dimensions a pattern moves past a fixed
// eye because it has nowhere else to go; in three, the eye can move through a
// pattern that is simply THERE. Same image, and it acquires a place.
//
// The payoff is the thing a screen cannot do: the ranks are all on the same cell
// grid, so as you move, near bars slide across far ones and the whole field goes
// into moiré and out again. That interference is a depth cue and a rhythm at the
// same time, and it is generated by nothing but parallax.
//
// The two bands survive as the upper and lower half of every rank, stepping in
// opposite directions on the same tick — the horizontal seam in the reference is
// the visitor's own eye level here, which puts them inside the split.
//
// ---- 360, AND THE LANE (2026-07-30) ----------------------------------------
//
// On direction: the pattern has to be all around the visitor, and the bars have
// to come close enough to be inside rather than in front of.
//
// It used to be a corridor: every rank sat in front of the standpoint, the
// nearest one six metres out, and the treadmill wrapped before anything reached
// you. Turning your head found white. Now the ranks run from thirty metres
// BEHIND the standpoint to thirty ahead and the bars stream through, so the
// pattern is in every direction you can look and the near ones pass at arm's
// length.
//
// THE LANE is what makes that safe, and it is the one thing here not to remove.
// Flow is along z, so a bar's whole path is determined by its x: any cell whose
// slab would come within LANE_HALF_WIDTH of the axis is simply never drawn.
// Nothing can ever intersect the visitor, and — this is the part that matters —
// nothing has to be culled or faded out next to their head either, which is the
// obvious alternative and is far more visible than the gap. What it costs is a
// clear channel straight ahead and straight behind; that channel closes with
// distance, because ranks further away have bars at every x, so the forward view
// fills in and only the first few metres read as a lane. Standing in it is the
// sequence.
//
// BOTH WRAPS ARE PAST THE FOG. New ranks appear at 32m ahead and retire at 30m
// behind, and fogFar is 26 — so a rank is already washed to the world's white
// before it is born and after it dies. That is the only reason a treadmill this
// short can surround the visitor without a visible seam, and it is why fogFar
// and the rank extents have to move together.
//
// AND THE WALK GOT SLOWER, from 1.5 m/s to 0.9. Not a style choice. Vection is
// driven hardest by PERIPHERAL flow, and a corridor ahead puts most of its
// motion near the centre of vision where the effect is weakest. A lattice that
// surrounds puts coherent flow across the whole retina at once, including bars
// sweeping past at 0.7m where the angular rate is enormous. Same scene, a much
// stronger stimulus, so the velocity had to come down to pay for the coverage.

// ---- the grid --------------------------------------------------------------

// How wide the pattern runs, in metres. Wider than the fog can see, so it has no
// ends — a barcode you can see the edge of is a poster.
const SPAN = 34

// Cell counts across that span, re-rolled on the grid tick. The reference swings
// between roughly 33 and 108 cells across a screen; this is the same swing
// expressed in metres — 0.35m slabs at the fine end, 1.4m at the chunky end.
const CELLS_MIN = 24
const CELLS_MAX = 96

// Fraction of cells lit. The reference's step(0.8, …) — a fifth. Raising this
// closes the lane and the visitor walks into a wall; the gaps are what make it
// something you can be inside.
const CELL_DUTY = 0.2

// Ranks, and how far apart they stand. 26 ranks at 2.4m is 62m of lattice, and
// it has to be that long now that it reaches behind the standpoint as well:
// both ends of the treadmill must sit outside the fog (see RANKS_BEHIND).
const RANK_COUNT = 26
const RANK_SPACING = 2.4

// The slab itself. Thin front-to-back so it reads as a LINE from the front and
// almost disappears edge-on as you pass it — which is exactly what a bar in a
// test pattern does when the image turns.
const SLAB_DEPTH = 0.1

// The two bands, split at just below eye height so the seam runs through the
// visitor's own sightline rather than above or below it.
//
// The extents are set so the NEAREST rank runs off the top and bottom of the
// view. At 4.8 and -1.9 the near bars ended inside the frame and the sequence
// read as looking at a wide object with white above and below it — the
// reference's bars run edge to edge, and being able to see where a bar stops is
// the difference between standing in a pattern and facing one. Checked against a
// projected preview at the standpoint's own eye height rather than by eye in the
// editor, where the framing is not the audience's.
const SEAM = 1.42
const UPPER_TOP = 6.4
const LOWER_BOTTOM = -3.6

// A visible gap at the seam, in metres. The reference has a hard edge there and
// it is one of the strongest things in the frame.
const SEAM_GAP = 0.07

// ---- the ticks -------------------------------------------------------------
//
// Two clocks, as in the reference: one steps the pattern sideways, the slower
// one re-rolls the grid itself.
//
// 2.6Hz rather than the reference's faster step. On a screen a hard jump is an
// event in an image; in a headset, at this size, it is a room rearranging
// itself, and it needs to be slow enough that the eye can follow one jump before
// the next. Also comfortably clear of the 15-25Hz photosensitivity band, which
// matters more here than anywhere else in the piece — this is the only sequence
// with large high-contrast areas changing at once.
const STEP_HZ = 2.6
const GRID_HZ = 0.85

// ---- the walk --------------------------------------------------------------
//
// The bars travel toward a stationary viewer, exactly as the tunnel's rings do.
// In an XR session the headset owns the camera pose, and moving it fights the
// visitor's own head.
//
// 0.9 m/s — a slow walk, down from 1.5 when the lattice went from a corridor
// ahead to something that surrounds. This is the only sequence in the piece with
// a large COHERENT flow across the visual field, which is the textbook vection
// trigger (see the comfort note in DataField.jsx), and surrounding the visitor
// moved that flow into the periphery where vection is generated most strongly.
// Everything that can be done to soften it is done: constant velocity through
// the middle, eased in and out at the ends, no rotation, and no vertical bob.
//
// NO HEAD BOB, deliberately, and this is the one place the brief gets argued
// with. A walk cycle in VR means oscillating the horizon against a vestibular
// system that knows the visitor is standing still, and it is one of the most
// reliable ways to make somebody ill in this medium. The walk has to be carried
// by the flow of the bars, which it is — passing a slab at arm's length at
// 1.5 m/s reads as walking without a single pixel of camera movement.
const WALK_SPEED = 0.9

// Where the treadmill wraps.
const CORRIDOR_LENGTH = RANK_COUNT * RANK_SPACING

// How far BEHIND the standpoint the lattice reaches before a rank retires and is
// reissued at the far end. Flow is toward +z, so this is the retirement line and
// `CORRIDOR_LENGTH - RANKS_BEHIND` (32.4m) is where a rank is born.
//
// Both numbers have to stay outside the fog, or a rank pops into being in air
// still clear enough to see it happen. The fog belongs to this sequence's
// edit-list row rather than to this file (`backdrop.fogFar`, 26 at the time of
// writing) — so if you lengthen the lattice, open the fog to match, and if you
// close the fog, shorten the lattice.
const RANKS_BEHIND = 30

// Half-width of the clear channel along the flow axis, in metres. A slab whose
// inner edge would fall inside this is never drawn, so nothing can pass through
// the visitor — see THE LANE at the top of this file.
//
// 0.7 rather than something tighter: it is measured from the standpoint's own
// axis, and a visitor leaning or taking the half-step a room-scale headset
// allows has to stay inside it. Anything under about 0.5 and a slab clips a
// shoulder, which in a headset is worse than a collision — the bar simply passes
// through you and the room stops being solid.
const LANE_HALF_WIDTH = 0.7

// Black on white, and it has to be TRUE black. The world is pure white and the
// fog blends everything toward it with distance, so a near-black bar is already
// a grey by the second rank — the value has to start at zero for the falloff to
// have anywhere to go.
const BAR_BLACK = '#000000'

/**
 * On or off for one cell.
 *
 * Integer avalanche, like the rest of the piece's noise — deterministic across
 * machines, and the same (cell, band) always gives the same answer, so the
 * pattern is reproducible.
 */
const hashCell = (cell, band) => {
    let h = Math.imul(cell ^ 0x9e3779b9, 0x85ebca6b) ^ Math.imul(band + 0x27d4eb2f, 0xc2b2ae35)
    h = Math.imul(h ^ (h >>> 15), 0x2545f491)
    return ((h ^ (h >>> 13)) >>> 0) / 4294967296
}

const BAND_COUNT = 2
const MAX_INSTANCES = RANK_COUNT * BAND_COUNT * CELLS_MAX

// Exported for the lane test, which is the one guard in this file worth having:
// the claim is that NO slab, at any of the grid sizes the re-roll can produce,
// ever reaches the visitor. That is checked arithmetically rather than by
// standing in it.
export const GRID_LIMITS = Object.freeze({
    span: SPAN,
    cellsMin: CELLS_MIN,
    cellsMax: CELLS_MAX,
    laneHalfWidth: LANE_HALF_WIDTH
})

/** Centre of one cell, in metres, on a grid of `cells` across SPAN. */
export const cellCentre = (cell, cellWidth) => -SPAN * 0.5 + (cell + 0.5) * cellWidth

/**
 * Does this cell's slab stay out of the visitor's channel?
 *
 * Measured to the slab's inner EDGE and not its centre — a chunky cell sitting
 * just outside the lane still reaches into it by half its width.
 */
export const clearsLane = (x, cellWidth) =>
    Math.abs(x) - cellWidth * 0.5 >= LANE_HALF_WIDTH

export default function TestPattern({ progress }) {
    const meshRef = useRef(null)

    const scratch = useMemo(() => ({
        matrix: new THREE.Matrix4(),
        position: new THREE.Vector3(),
        quaternion: new THREE.Quaternion(),
        scale: new THREE.Vector3()
    }), [])

    useFrame(({ clock }) => {
        const mesh = meshRef.current
        if (!mesh) return

        const local = progress
        if (local === null) return

        const time = clock.getElapsedTime()

        const envelope = smoothstep(0, 0.12, local) * smoothstep(1, 0.88, local)
        mesh.material.opacity = envelope

        // The grid re-roll. Quantised to its own tick so the cell size CHANGES
        // rather than drifts — a grid that eases between sizes is a zoom, and
        // the reference's jump between fine and chunky is the point.
        const gridTick = Math.floor(time * GRID_HZ)
        const cells = CELLS_MIN
            + Math.floor(hashCell(gridTick, 991) * (CELLS_MAX - CELLS_MIN))
        const cellWidth = SPAN / cells

        // The sideways step, in whole cells, opposite per band.
        const step = Math.floor(time * STEP_HZ)

        // How far the corridor has travelled. Eased at both ends: constant
        // velocity is comfortable, but starting AT velocity is a lurch, and the
        // ease is the difference between the room beginning to move and the room
        // already moving when it appears.
        const pace = smoothstep(0, 0.14, local) * smoothstep(1, 0.86, local)
        const travelled = time * WALK_SPEED * pace

        let instance = 0

        for (let rank = 0; rank < RANK_COUNT; rank++) {
            // Treadmill, now running THROUGH the standpoint rather than up to
            // it: a rank is born at -(CORRIDOR_LENGTH - RANKS_BEHIND) well
            // beyond the fog, streams past the visitor, and retires
            // RANKS_BEHIND metres behind them, equally out of sight. 26 ranks
            // read as a lattice without end in either direction.
            const z = ((rank * RANK_SPACING + travelled) % CORRIDOR_LENGTH)
                - (CORRIDOR_LENGTH - RANKS_BEHIND)

            for (let band = 0; band < BAND_COUNT; band++) {
                // Opposite directions, one tick, as in the reference.
                const direction = band === 0 ? 1 : -1
                const height = band === 0
                    ? UPPER_TOP - SEAM - SEAM_GAP
                    : SEAM - SEAM_GAP - LOWER_BOTTOM
                const centre = band === 0
                    ? SEAM + SEAM_GAP + height * 0.5
                    : LOWER_BOTTOM + height * 0.5

                for (let cell = 0; cell < cells; cell++) {
                    if (instance >= MAX_INSTANCES) break

                    const x = cellCentre(cell, cellWidth)

                    // THE LANE. Flow is along z, so a slab's entire path is
                    // decided by its x — testing it here once means nothing has
                    // to be culled later while it is next to somebody's head.
                    if (!clearsLane(x, cellWidth)) continue

                    // The rank is folded into the hash so every rank carries a
                    // different barcode. Identical ranks would line up into
                    // corridors of slab, and the moiré that makes this worth
                    // doing in three dimensions comes from them NOT agreeing.
                    const lit = hashCell(
                        cell - step * direction + rank * 131,
                        band
                    ) < CELL_DUTY

                    if (!lit) continue

                    scratch.position.set(x, centre, z)
                    // Full cell width, so adjacent lit cells MERGE into one
                    // wide bar with no seam. That merge is where the reference's
                    // range of bar widths comes from.
                    scratch.scale.set(cellWidth, height, SLAB_DEPTH)
                    scratch.quaternion.identity()
                    scratch.matrix.compose(scratch.position, scratch.quaternion, scratch.scale)
                    mesh.setMatrixAt(instance, scratch.matrix)
                    instance++
                }
            }
        }

        // Everything past the last written instance is simply NOT DRAWN. This
        // replaces the old approach of parking unused instances at zero scale,
        // which composed and uploaded ~4,400 zero matrices every frame of the
        // beat — the piece's single biggest per-frame JS cost, spent drawing
        // nothing. An undrawn instance cannot freeze mid-corridor however
        // stale its matrix is, which was the hazard the parking existed for.
        mesh.count = instance
        mesh.instanceMatrix.needsUpdate = true
    })

    if (progress === null) return null

    return (
        <group>
            <instancedMesh
                ref={meshRef}
                args={[undefined, undefined, MAX_INSTANCES]}
                frustumCulled={false}
            >
                <boxGeometry args={[1, 1, 1]} />
                {/* FOGGED, alone among this piece's emissive-looking sequences,
                    and it is the fog that makes the room white rather than the
                    backdrop. Every other sequence turns fog off because its
                    content is light standing in dark air; here the content is
                    the only dark thing in the frame, so letting the distance
                    wash it toward the world colour is what builds the void —
                    near bars are true black, the tenth rank is a grey, and there
                    is no horizon anywhere.

                    Unlit basic material: a white room lit by an ambient fill
                    would put a value on the slab faces and they would stop being
                    marks and start being objects. */}
                <meshBasicMaterial
                    color={BAR_BLACK}
                    transparent
                    opacity={0}
                    toneMapped={false}
                />
            </instancedMesh>
        </group>
    )
}
